[package]

name = "heroku-rust-cargo-hello"
version = "1.0.0"
authors = ["me@example.com"]

[[bin]]
name = "hello"

[dependencies]
iron = "*"

[dependencies.router]
git = "https://github.com/iron/router.git"
